all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: 192.168.0.50
          ansible_user: root
          proxmox_node: server
          proxmox_api_host: "192.168.0.50:8006"
          proxmox_api_user: "root@pam"
    docker_vm:
      hosts:
        homelab:
          ansible_host: 192.168.0.31
          ansible_user: daniel
    adguard_lxc:
      hosts:
        adguard:
          ansible_host: 192.168.0.51
          ansible_user: root
