all:
  children:
    docker_vm:
      hosts:
        homelab:
          ansible_host: 192.168.1.50
          ansible_user: youruser
    adguard:
      hosts:
        adguard:
          ansible_host: 192.168.1.2
          ansible_user: root
