all:
  children:
    docker_vm:
      hosts:
        homelab:
          ansible_host: 192.168.0.31
          ansible_user: daniel
    adguard_lxc:
      hosts:
        adguard:
          ansible_host: 192.168.0.51
          ansible_user: root
