---
- name: Deploy services on Docker VM
  hosts: docker_vm
  become: true
  roles:
    - tailscale_certs

  tasks:
    - name: Deploy docker compose stacks
      ansible.builtin.include_role:
        name: docker_stack
      loop: "{{ docker_stacks }}"
      loop_control:
        loop_var: docker_stack_item